apiVersion: apps/v1
kind: Deployment
metadata:
  name: -service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: mohamedensias/inventory-service:latest
          ports:
            - containerPort: 8082
