services:
  discovery-service:
    container_name: discovery-service
    image: discovery-service-image
    networks:
      - microservices-net
    ports:
      - "8761:8761"

  customer-service:
    container_name: customer-service
    image: customer-service-image
    networks:
      - microservices-net
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service

  inventory-service:
    container_name: inventory-service
    image: inventory-service-image
    networks:
      - microservices-net
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service

  billing-service:
    container_name: billing-service
    image: billing-service-image
    networks:
      - microservices-net
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - customer-service
      - inventory-service

  gateway-service:
    container_name: gateway-service
    image: gateway-service-image
    networks:
      - microservices-net
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service

networks:
  microservices-net: