version: "3.8"
services:
  gateway-service:
    build: ./gateway-service
    ports:
      - "8888:8888"

  billing-service:
    build: ./billing-service
    ports:
      - "8081:8081"

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8082"

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
