version: "3.8"

services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"

  gateway-service:
    build: ./gateway-service
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service

  customer-service:
    build: ./customer-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service

  billing-service:
    build: ./billing-service
    ports:
      - "8083:8083"
    depends_on:
      - customer-service
      - inventory-service
      - discovery-service
