global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.88:8888']  # Match the container name and port

  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.88:8761']  # Eureka usually runs on 8761

  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.88:8081']

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.88:8082']

  - job_name: 'billing-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.1.88:8083' ]

  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.88:9090']
