global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8888']

  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['127.0.0.1:8761']  # it should be a static IP

  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer-service:8081']

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8082']

  - job_name: 'billing-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'billing-service:8083' ]

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']  # it should be a static IP
