apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
      nodePort: 30061  # Optional: manually set a port (range 30000–32767)
  type: ClusterIP