name: DEPLOYMENT

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH and deploy on remote VM
        env:
          VM_IP: ${{ secrets.VM_IP }}
          VM_NAME: ${{ secrets.VM_NAME }}
          PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no $VM_NAME@$VM_IP << 'EOF'
            cd $PROJECT_DIR
            git pull origin main
            docker stop flask_mockupia_container || true
            docker rm flask_mockupia_container || true
            docker build -t flask-mockupia:latest .
            docker run -d -p 5000:5000 --name flask_mockupia_container flask-mockupia:latest
          EOF
